### ISSUE TITLE
401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json

### ISSUE THREAD

**Issue by yzhao30** [YangLing0818/RPG-DiffusionMaster#11]
Follow the instruction, but got the error:

```bash
creating model quickly: OSError
Traceback (most recent call last):
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status
    response.raise_for_status()
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/transformers/utils/hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1374, in hf_hub_download
    raise head_call_error
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1247, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1624, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 402, in _request_wrapper
    response = _request_wrapper(
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 426, in _request_wrapper
    hf_raise_for_status(response)
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 320, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-65b20d86-1b897ebc0e79ac4164603e75;8aa129ba-e901-46ae-8e3f-2e433b67d303)

Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/RPG-DiffusionMaster/RPG.py", line 338, in <module>
    initialize(model_name=model_name)
  File "/home/user/RPG-DiffusionMaster/RPG.py", line 92, in initialize
    modules.sd_models.load_model(model_name=model_name)
  File "/home/user/RPG-DiffusionMaster/modules/sd_models.py", line 636, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/home/user/RPG-DiffusionMaster/repositories/stable-diffusion-stability-ai/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/user/RPG-DiffusionMaster/repositories/generative-models/sgm/models/diffusion.py", line 59, in __init__
    self.conditioner = instantiate_from_config(
  File "/home/user/RPG-DiffusionMaster/repositories/generative-models/sgm/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/user/RPG-DiffusionMaster/repositories/generative-models/sgm/modules/encoders/modules.py", line 79, in __init__
    embedder = instantiate_from_config(embconfig)
  File "/home/user/RPG-DiffusionMaster/repositories/generative-models/sgm/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/user/RPG-DiffusionMaster/repositories/generative-models/sgm/modules/encoders/modules.py", line 349, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "/home/user/RPG-DiffusionMaster/modules/sd_disable_initialization.py", line 68, in CLIPTextModel_from_pretrained
    res = self.CLIPTextModel_from_pretrained(None, *model_args, config=pretrained_model_name_or_path, state_dict={}, **kwargs)
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2928, in from_pretrained
    resolved_config_file = cached_file(
  File "/home/user/.conda/envs/RPG/lib/python3.9/site-packages/transformers/utils/hub.py", line 406, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

Failed to create model quickly; will retry using slow method.
```

Does this matter and any fix to it? Thanks.

**Comment by RahulSinghalChicago** [comment]
I have the same error at the moment and it looks like it's trying to download a model that is set to None. maybe one of the arguments' default setting needs to be set.  However, my run of `--demo` still generates.

**Comment by yunbinmo** [comment]
Having the same error, but the generation can still be done

**Comment by adammenges** [comment]
same error here too

**Comment by NaniteLion** [comment]
same error here too

**Comment by wly-ai-bj** [comment]
same error

**Comment by rkim-n** [comment]
I'm getting below error, how to go about fixing it?
model_id = "helenai/Linaqruf-anything-v3.0-ov"
pipe = RegionalGenerator(model_id, dtype=torch.float32, device="cpu")

tokenizer/tokenizer_config.json: 100%
 819/819 [00:00<00:00, 19.8kB/s]
tokenizer/vocab.json: 100%
 1.06M/1.06M [00:00<00:00, 1.26MB/s]
tokenizer/merges.txt: 100%
 525k/525k [00:00<00:00, 1.32MB/s]
tokenizer/special_tokens_map.json: 100%
 472/472 [00:00<00:00, 20.8kB/s]
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    285     try:
--> 286         response.raise_for_status()
    287     except HTTPError as e:

15 frames
HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/helenai/Linaqruf-anything-v3.0-ov/resolve/main/text_encoder/config.json
The above exception was the direct cause of the following exception:

EntryNotFoundError                        Traceback (most recent call last)
EntryNotFoundError: 404 Client Error. (Request ID: Root=1-65f8d6b9-1847ac8a19f2cc4f18e35042;6d2590fe-c17d-4737-81ec-bd2ef18f15a3)

Entry Not Found for url: https://huggingface.co/helenai/Linaqruf-anything-v3.0-ov/resolve/main/text_encoder/config.json.

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py](https://localhost:8080/#) in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_gated_repo, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)
    450         if revision is None:
    451             revision = "main"
--> 452         raise EnvironmentError(
    453             f"{path_or_repo_id} does not appear to have a file named {full_filename}. Checkout "
    454             f"'[https://huggingface.co/{path_or_repo_id}/{revision}'](https://huggingface.co/%7Bpath_or_repo_id%7D/%7Brevision%7D') for available files."

OSError: helenai/Linaqruf-anything-v3.0-ov does not appear to have a file named text_encoder/config.json. Checkout 'https://huggingface.co/helenai/Linaqruf-anything-v3.0-ov/main' for available files.
