### ISSUE TITLE
Error loading script: latent.py

### ISSUE THREAD

**Issue by yizhangliu** [YangLing0818/RPG-DiffusionMaster#9]
When I run " python RPG.py --demo", I got some errors  like:

              *** Error loading script: latent.py
                  Traceback (most recent call last):
                    File "/home/xl_projects/RPG-DiffusionMaster/modules/scripts.py", line 470, in load_scripts
                      script_module = script_loading.load_module(scriptfile.path)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/home/xl_projects/RPG-DiffusionMaster/modules/script_loading.py", line 10, in load_module
                      module_spec.loader.exec_module(module)
                    File "<frozen importlib._bootstrap_external>", line 940, in exec_module
                    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
                    File "/home/xl_projects/RPG-DiffusionMaster/scripts/latent.py", line 12, in <module>
                      import scripts.attention as att
                  ModuleNotFoundError: No module named 'scripts.attention'

Why?

**Comment by yizhangliu** [comment]
It was my mistake
